### ISSUE TITLE
Re: I can't install a plugin :-(

### ISSUE THREAD

**Issue by BoweFrankema** [WeFoster/wefoster#36]
-- Please reply above this line --

Hello Bowe,

We have received your support ticket! You can continue this
conversation via this email or through your WeFoster Customer
Dashboard. 

We will get back to you as soon as possible.

Thanks for your patience!

-----------------------------------------------------------
## Bowe Frankema replied, on May 31 @ 8:22am (GMT+1):

I need help!

-----------------------------------------------------------

**Comment by slaFFik** [comment]
And how about this?

**Comment by BoweFrankema** [comment]
I was experimenting with forwarding an HelpScout ticket into a GitHub issue.. which works 👯
